# Azure pipeline to deploy to Prod Web app on Azure

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
-
- task: Docker@2
  inputs:
    containerRegistry: 'usharegistry'
    repository: 'nodeapp'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
- task: AzureWebAppContainer@1
  inputs:
    azureSubscription: 'RMPM'
    appName: 'AppWithContainer'
    containers: 'usharegistry.azurecr.io/nodeapp:$(Build.BuildId)'
