name: Build and deploy Docker app to Azure

on: push

# CONFIGURATION
# For help, go to https://github.com/Azure/Actions
#
# Set up the following secrets in your repository:
#   AZURE_CREDENTIALS, REGISTRY_USERNAME, REGISTRY_PASSWORD

jobs:
  build-and-deploy-to-dev:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
     # Authentication to Azure and Container Registry
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: azure/docker-login@v1
      with:
        login-server: actionregistry.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    # Docker Build & Push Image to ACR
    - run: |
        docker build . -t actionregistry.azurecr.io/nodejsapp:${{ github.sha }}
        docker push actionregistry.azurecr.io/nodejsapp:${{ github.sha }}
        
    # Provision a new Web App using Az CLI
    - name: Azure CLI script to create a new Web App for Container
      uses: azure/CLI@v0-beta
      with:
        azcliversion: latest
        inlineScript: |
          az account show
          az webapp list
          az webapp create --resource-group ActionsDemo --plan ActionPlan --name AppWithContainer1  -i nginx
          
    - uses: azure/webapps-container-deploy@v1
      with: 
        app-name: AppWithContainer1 
        images: 'actionregistry.azurecr.io/nodejsapp:${{ github.sha }}'
